/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PurchaseFrequencyIndexImport } from './routes/purchase-frequency/index'
import { Route as CustomersIndexImport } from './routes/customers/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PurchaseFrequencyIndexRoute = PurchaseFrequencyIndexImport.update({
  id: '/purchase-frequency/',
  path: '/purchase-frequency/',
  getParentRoute: () => rootRoute,
} as any)

const CustomersIndexRoute = CustomersIndexImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersIndexImport
      parentRoute: typeof rootRoute
    }
    '/purchase-frequency/': {
      id: '/purchase-frequency/'
      path: '/purchase-frequency'
      fullPath: '/purchase-frequency'
      preLoaderRoute: typeof PurchaseFrequencyIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersIndexRoute
  '/purchase-frequency': typeof PurchaseFrequencyIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof CustomersIndexRoute
  '/purchase-frequency': typeof PurchaseFrequencyIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/purchase-frequency/': typeof PurchaseFrequencyIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/customers' | '/purchase-frequency'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/customers' | '/purchase-frequency'
  id: '__root__' | '/' | '/customers/' | '/purchase-frequency/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  PurchaseFrequencyIndexRoute: typeof PurchaseFrequencyIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  PurchaseFrequencyIndexRoute: PurchaseFrequencyIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/customers/",
        "/purchase-frequency/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/customers/": {
      "filePath": "customers/index.tsx"
    },
    "/purchase-frequency/": {
      "filePath": "purchase-frequency/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
